DROP TABLE IF EXISTS CUSTOMER;
 
CREATE TABLE CUSTOMER (
  ID 			INT 			AUTO_INCREMENT PRIMARY KEY,
  NAME 			VARCHAR(250) 		NOT NULL,
  SURNAME 		VARCHAR(250) 		NOT NULL,
  PHOTO 		INT 				DEFAULT 0,
  CREATION_USER VARCHAR(250) 		DEFAULT NULL,
  MODIFICATION_USER VARCHAR(250) 	DEFAULT NULL
);



DROP TABLE IF EXISTS USER;
 
CREATE TABLE USER (
  ID 			INT 			AUTO_INCREMENT PRIMARY KEY,
  NAME 			VARCHAR(250) 		NOT NULL,
  PASS 			VARCHAR(250) 		NOT NULL,
  ROLE			INT					NOT NULL
);


